module.exports = [
  {
    fileNameBase: 'agency',
    collection: 'gtfs-agencies'
  }, {
    fileNameBase: 'calendar_dates',
    collection: 'gtfs-calendardates'
  }, {
    fileNameBase: 'calendar',
    collection: 'gtfs-calendars'
  }, {
    fileNameBase: 'fare_attributes',
    collection: 'gtfs-fareattributes'
  }, {
    fileNameBase: 'fare_rules',
    collection: 'gtfs-farerules'
  }, {
    fileNameBase: 'feed_info',
    collection: 'gtfs-feedinfos'
  }, {
    fileNameBase: 'frequencies',
    collection: 'gtfs-frequencies'
  }, {
    fileNameBase: 'routes',
    collection: 'gtfs-routes'
  }, {
    fileNameBase: 'shapes',
    collection: 'gtfs-shapes'
  }, {
    fileNameBase: 'stop_times',
    collection: 'gtfs-stoptimes'
  }, {
    fileNameBase: 'stops',
    collection: 'gtfs-stops'
  }, {
    fileNameBase: 'transfers',
    collection: 'gtfs-transfers'
  }, {
    fileNameBase: 'trips',
    collection: 'gtfs-trips'
  }, {
    fileNameBase: 'stop_attributes',
    collection: 'gtfs-stopattributes',
    nonstandard: true
  }, {
    fileNameBase: 'timetables',
    collection: 'gtfs-timetables',
    nonstandard: true
  }, {
    fileNameBase: 'timetable_pages',
    collection: 'gtfs-timetablepages',
    nonstandard: true
  }, {
    fileNameBase: 'timetable_stop_order',
    collection: 'gtfs-timetablestoporders',
    nonstandard: true
  }
];
